# Day 1 - Python for Data Refresher
## Pandas Basics

### Objectives
- Read CSV files
- Load DataFrames
- Explore data
- Filter rows
- Sort data
- Group data

In [30]:
import pandas as pd

Load Dataset

In [31]:
df = pd.read_csv("../resources/sales-messy.csv")
df.head()

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
0,ORD-1116,2023-10-22,Customer_687,Mumbai,West,Karan Singh,Electronics,Headphones,8.0,5699.16,0.0,45593.28,Net Banking,Returned
1,ORD-1121,2023-08-29,Customer_746,Ahmedabad,west,Neha Joshi,Sports,Cycle,6.0,14909.64,5.0,84984.95,UPI,Delivered
2,ORD-1123,2023-01-22,Customer_929,Lucknow,North,Neha Joshi,Sports,Cycle,8.0,15081.47,20.0,96521.41,Card,Delivered
3,ORD-1227,2023-10-13,Customer_556,Jaipur,North,NaN,Electronics,Laptop,4.0,66604.54,20.0,213134.53,UPI,Returned
4,ORD-1067,2023-03-22,Customer_277,Chandigarh,North,Sneha Patel,Sports,Cricket Bat,4.0,2235.29,10.0,8047.04,upi,Delivered

In [32]:
import pandas as pd
df = pd.read_csv("../resources/sales-messy.csv")
df.head()

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
0,ORD-1116,2023-10-22,Customer_687,Mumbai,West,Karan Singh,Electronics,Headphones,8.0,5699.16,0.0,45593.28,Net Banking,Returned
1,ORD-1121,2023-08-29,Customer_746,Ahmedabad,west,Neha Joshi,Sports,Cycle,6.0,14909.64,5.0,84984.95,UPI,Delivered
2,ORD-1123,2023-01-22,Customer_929,Lucknow,North,Neha Joshi,Sports,Cycle,8.0,15081.47,20.0,96521.41,Card,Delivered
3,ORD-1227,2023-10-13,Customer_556,Jaipur,North,NaN,Electronics,Laptop,4.0,66604.54,20.0,213134.53,UPI,Returned
4,ORD-1067,2023-03-22,Customer_277,Chandigarh,North,Sneha Patel,Sports,Cricket Bat,4.0,2235.29,10.0,8047.04,upi,Delivered

In [33]:
df.tail()

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
258,ORD-1021,2023-05-02,Customer_516,Mumbai,West,Ravi Kumar,sports,Cricket Bat,9.0,Rs. 2303.18,0.0,20728.62,Net Banking,Returned
259,ORD-1189,2023-04-03,NaN,Delhi,North,Ravi Kumar,Sports,Cricket Bat,8.0,2153.16,0.0,17225.28,Net Banking,Delivered
260,ORD-1072,2023-08-12,Customer_193,Lucknow,North,NaN,furniture,Sofa,5.0,26242.36,NaN,124651.21,CASH,Delivered
261,ORD-1107,2023-10-15,Customer_786,Jaipur,North,Divya Iyer,clothing,Formal Shirt,3.0,Rs. 1147.2,20.0,2753.28,Cash,Returned
262,ORD-1103,25/02/2023,Customer_829,Kolkata,East,Neha Joshi,Clothings,Formal Shirt,8.0,1191.15,15.0,8099.82,net banking,Delivered

In [34]:
df.shape

(263, 14)

In [35]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'city', 'region',
       'salesperson', 'category', 'product', 'quantity', 'unit_price',
       'discount_pct', 'total_amount', 'payment_mode', 'status'],
      dtype='str')

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       260 non-null    str
 1   order_date     260 non-null    str
 2   customer_name  248 non-null    str
 3   city           252 non-null    str
 4   region         260 non-null    str
 5   salesperson    250 non-null    str
 6   category       260 non-null    str
 7   product        260 non-null    str
 8   quantity       260 non-null    float64
 9   unit_price     260 non-null    str
 10  discount_pct   245 non-null    float64
 11  total_amount   260 non-null    float64
 12  payment_mode   253 non-null    str
 13  status         251 non-null    str
dtypes: float64(3), str(11)
memory usage: 52.3 KB

In [37]:
df.describe()

         quantity  discount_pct  total_amount
count  260.000000    245.000000  2.600000e+02
mean     5.350000     10.265306  5.275100e+05
std      3.011657      7.145374  5.321120e+06
min     -3.000000      0.000000  1.326200e+02
25%      3.000000      5.000000  7.113465e+03
50%      5.000000     10.000000  2.040351e+04
75%      8.000000     15.000000  7.331808e+04
max     10.000000     20.000000  8.338896e+07

In [38]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'city', 'region',
       'salesperson', 'category', 'product', 'quantity', 'unit_price',
       'discount_pct', 'total_amount', 'payment_mode', 'status'],
      dtype='str')

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       260 non-null    str
 1   order_date     260 non-null    str
 2   customer_name  248 non-null    str
 3   city           252 non-null    str
 4   region         260 non-null    str
 5   salesperson    250 non-null    str
 6   category       260 non-null    str
 7   product        260 non-null    str
 8   quantity       260 non-null    float64
 9   unit_price     260 non-null    str
 10  discount_pct   245 non-null    float64
 11  total_amount   260 non-null    float64
 12  payment_mode   253 non-null    str
 13  status         251 non-null    str
dtypes: float64(3), str(11)
memory usage: 52.3 KB

In [40]:
df.isnull().sum()

order_id          3
order_date        3
customer_name    15
city             11
region            3
salesperson      13
category          3
product           3
quantity          3
unit_price        3
discount_pct     18
total_amount      3
payment_mode     10
status           12
dtype: int64

Filtering

In [41]:
# Convert columns to numeric (only if needed)
df["unit_price"] = pd.to_numeric(df["unit_price"], errors="coerce")
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")

# Products with unit_price > 1000
df[df["unit_price"] > 1000]

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
0,ORD-1116,2023-10-22,Customer_687,Mumbai,West,Karan Singh,Electronics,Headphones,8.0,5699.16,0.0,45593.28,Net Banking,Returned
1,ORD-1121,2023-08-29,Customer_746,Ahmedabad,west,Neha Joshi,Sports,Cycle,6.0,14909.64,5.0,84984.95,UPI,Delivered
2,ORD-1123,2023-01-22,Customer_929,Lucknow,North,Neha Joshi,Sports,Cycle,8.0,15081.47,20.0,96521.41,Card,Delivered
3,ORD-1227,2023-10-13,Customer_556,Jaipur,North,NaN,Electronics,Laptop,4.0,66604.54,20.0,213134.53,UPI,Returned
4,ORD-1067,2023-03-22,Customer_277,Chandigarh,North,Sneha Patel,Sports,Cricket Bat,4.0,2235.29,10.0,8047.04,upi,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,ORD-1211,2023-04-17,Customer_870,NaN,North,Ravi Kumar,Electronics,Tablet,3.0,20934.45,10.0,56523.02,Upi,Delivered
256,ORD-1122,2023-01-30,Customer_951,Delhi,North,Divya Iyer,Office Supplies,File Cabinet,5.0,3184.61,15.0,13534.59,UPI,Delivered
259,ORD-1189,2023-04-03,NaN,Delhi,North,Ravi Kumar,Sports,Cricket Bat,8.0,2153.16,0.0,17225.28,Net Banking,Delivered
260,ORD-1072,2023-08-12,Customer_193,Lucknow,North,NaN,furniture,Sofa,5.0,26242.36,NaN,124651.21,CASH,Delivered
262,ORD-1103,25/02/2023,Customer_829,Kolkata,East,Neha Joshi,Clothings,Formal Shirt,8.0,1191.15,15.0,8099.82,net banking,Delivered

In [42]:
# Products with quantity >= 5
df[df["quantity"] >= 5]

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
0,ORD-1116,2023-10-22,Customer_687,Mumbai,West,Karan Singh,Electronics,Headphones,8.0,5699.16,0.0,45593.28,Net Banking,Returned
1,ORD-1121,2023-08-29,Customer_746,Ahmedabad,west,Neha Joshi,Sports,Cycle,6.0,14909.64,5.0,84984.95,UPI,Delivered
2,ORD-1123,2023-01-22,Customer_929,Lucknow,North,Neha Joshi,Sports,Cycle,8.0,15081.47,20.0,96521.41,Card,Delivered
9,ORD-1102,2023-08-20,Customer_729,Lucknow,North,Sneha Patel,electronic,Headphones,6.0,5551.52,20.0,26647.30,Cash,Pending
10,ORD-1025,2023-02-11,Customer_773,Pune,West,Karan Singh,Electronics,Smartwatch,10.0,11447.69,20.0,91581.52,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,ORD-1122,2023-01-30,Customer_951,Delhi,North,Divya Iyer,Office Supplies,File Cabinet,5.0,3184.61,15.0,13534.59,UPI,Delivered
258,ORD-1021,2023-05-02,Customer_516,Mumbai,West,Ravi Kumar,sports,Cricket Bat,9.0,NaN,0.0,20728.62,Net Banking,Returned
259,ORD-1189,2023-04-03,NaN,Delhi,North,Ravi Kumar,Sports,Cricket Bat,8.0,2153.16,0.0,17225.28,Net Banking,Delivered
260,ORD-1072,2023-08-12,Customer_193,Lucknow,North,NaN,furniture,Sofa,5.0,26242.36,NaN,124651.21,CASH,Delivered
262,ORD-1103,25/02/2023,Customer_829,Kolkata,East,Neha Joshi,Clothings,Formal Shirt,8.0,1191.15,15.0,8099.82,net banking,Delivered

In [43]:
# Products satisfying both conditions
df[(df["unit_price"] > 1000) & (df["quantity"] >= 5)]

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
0,ORD-1116,2023-10-22,Customer_687,Mumbai,West,Karan Singh,Electronics,Headphones,8.0,5699.16,0.0,45593.28,Net Banking,Returned
1,ORD-1121,2023-08-29,Customer_746,Ahmedabad,west,Neha Joshi,Sports,Cycle,6.0,14909.64,5.0,84984.95,UPI,Delivered
2,ORD-1123,2023-01-22,Customer_929,Lucknow,North,Neha Joshi,Sports,Cycle,8.0,15081.47,20.0,96521.41,Card,Delivered
9,ORD-1102,2023-08-20,Customer_729,Lucknow,North,Sneha Patel,electronic,Headphones,6.0,5551.52,20.0,26647.30,Cash,Pending
10,ORD-1025,2023-02-11,Customer_773,Pune,West,Karan Singh,Electronics,Smartwatch,10.0,11447.69,20.0,91581.52,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,ORD-1215,11/21/2023,Customer_857,Kolkata,East,Ravi Kumar,Furniture,Office Chair,5.0,8398.00,5.0,39890.50,Net Banking,Delivered
256,ORD-1122,2023-01-30,Customer_951,Delhi,North,Divya Iyer,Office Supplies,File Cabinet,5.0,3184.61,15.0,13534.59,UPI,Delivered
259,ORD-1189,2023-04-03,NaN,Delhi,North,Ravi Kumar,Sports,Cricket Bat,8.0,2153.16,0.0,17225.28,Net Banking,Delivered
260,ORD-1072,2023-08-12,Customer_193,Lucknow,North,NaN,furniture,Sofa,5.0,26242.36,NaN,124651.21,CASH,Delivered
262,ORD-1103,25/02/2023,Customer_829,Kolkata,East,Neha Joshi,Clothings,Formal Shirt,8.0,1191.15,15.0,8099.82,net banking,Delivered

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       260 non-null    str
 1   order_date     260 non-null    str
 2   customer_name  248 non-null    str
 3   city           252 non-null    str
 4   region         260 non-null    str
 5   salesperson    250 non-null    str
 6   category       260 non-null    str
 7   product        260 non-null    str
 8   quantity       260 non-null    float64
 9   unit_price     240 non-null    float64
 10  discount_pct   245 non-null    float64
 11  total_amount   260 non-null    float64
 12  payment_mode   253 non-null    str
 13  status         251 non-null    str
dtypes: float64(4), str(10)
memory usage: 50.4 KB

Sorting

In [53]:
edf_copy = df.sort_values(by="unit_price")    # Ascending
df_desc = df.sort_values(by="unit_price", ascending=False)   # Descending
display(df)
display(df_copy)
display(df_desc)

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
0,ORD-1116,2023-10-22,Customer_687,Mumbai,West,Karan Singh,Electronics,Headphones,8.0,5699.16,0.0,45593.28,Net Banking,Returned
1,ORD-1121,2023-08-29,Customer_746,Ahmedabad,west,Neha Joshi,Sports,Cycle,6.0,14909.64,5.0,84984.95,UPI,Delivered
2,ORD-1123,2023-01-22,Customer_929,Lucknow,North,Neha Joshi,Sports,Cycle,8.0,15081.47,20.0,96521.41,Card,Delivered
3,ORD-1227,2023-10-13,Customer_556,Jaipur,North,NaN,Electronics,Laptop,4.0,66604.54,20.0,213134.53,UPI,Returned
4,ORD-1067,2023-03-22,Customer_277,Chandigarh,North,Sneha Patel,Sports,Cricket Bat,4.0,2235.29,10.0,8047.04,upi,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,ORD-1021,2023-05-02,Customer_516,Mumbai,West,Ravi Kumar,sports,Cricket Bat,9.0,NaN,0.0,20728.62,Net Banking,Returned
259,ORD-1189,2023-04-03,NaN,Delhi,North,Ravi Kumar,Sports,Cricket Bat,8.0,2153.16,0.0,17225.28,Net Banking,Delivered
260,ORD-1072,2023-08-12,Customer_193,Lucknow,North,NaN,furniture,Sofa,5.0,26242.36,NaN,124651.21,CASH,Delivered
261,ORD-1107,2023-10-15,Customer_786,Jaipur,North,Divya Iyer,clothing,Formal Shirt,3.0,NaN,20.0,2753.28,Cash,Returned
262,ORD-1103,25/02/2023,Customer_829,Kolkata,East,Neha Joshi,Clothings,Formal Shirt,8.0,1191.15,15.0,8099.82,net banking,Delivered

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
173,ORD-1223,07-Oct-23,Customer_798,Ahmedabad,West,Ravi Kumar,Office Supplies,Pen Set,2.0,145.50,20.0,232.80,Cash,Returned
57,ORD-1061,2023-04-09,Customer_222,Patna,East,Divya Iyer,Office Supplies,Pen Set,5.0,145.96,10.0,656.82,Card,Delivered
31,ORD-1173,21-10-2023,Customer_504,Ahmedabad,West,Karan Singh,Office Supplies,Pen Set,9.0,146.82,10.0,1189.24,UPI,Delivered
105,ORD-1160,13/06/2023,Customer_577,Bhubaneswar,East,Sneha Patel,Office Supplies,Pen Set,6.0,150.92,20.0,724.42,Cash,Delivered
47,ORD-1019,2023-11-27,Customer_162,Surat,West,Priya Nair,Office Supplies,Pen Set,8.0,152.60,0.0,1220.80,Net Banking,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,ORD-1158,2023-06-04,Customer_350,Surat,West,Neha Joshi,Sport,Cricket Bat,9.0,NaN,10.0,18072.88,Net Banking,Delivered
252,ORD-1203,2023-12-17,Customer_363,Bhubaneswar,East,Divya Iyer,furniture,Sofa,8.0,NaN,20.0,162473.73,Net Banking,Returned
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,ORD-1021,2023-05-02,Customer_516,Mumbai,West,Ravi Kumar,sports,Cricket Bat,9.0,NaN,0.0,20728.62,Net Banking,Returned
261,ORD-1107,2023-10-15,Customer_786,Jaipur,North,Divya Iyer,clothing,Formal Shirt,3.0,NaN,20.0,2753.28,Cash,Returned

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
108,ORD-1036,2023-05-16,Customer_211,NaN,East,Amit Sharma,Electronics,Laptop,3.0,68006.47,20.0,163215.53,Net Banking,Delivered
58,ORD-1017,2023-06-19,Customer_626,Bangalore,South,Priya Nair,Electronics,Laptop,4.0,67635.23,0.0,270540.92,Netbanking,Delivered
72,ORD-1105,2023-07-31,Customer_947,Pune,West,Divya Iyer,Electronics,Laptop,7.0,67522.59,15.0,401759.41,Net Banking,Returned
8,ORD-1010,2023-08-05,Customer_494,Mumbai,west,Priya Nair,Electronics,Laptop,3.0,66898.52,5.0,190660.78,Net Banking,Pending
3,ORD-1227,2023-10-13,Customer_556,Jaipur,North,NaN,Electronics,Laptop,4.0,66604.54,20.0,213134.53,UPI,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,ORD-1158,2023-06-04,Customer_350,Surat,West,Neha Joshi,Sport,Cricket Bat,9.0,NaN,10.0,18072.88,Net Banking,Delivered
252,ORD-1203,2023-12-17,Customer_363,Bhubaneswar,East,Divya Iyer,furniture,Sofa,8.0,NaN,20.0,162473.73,Net Banking,Returned
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,ORD-1021,2023-05-02,Customer_516,Mumbai,West,Ravi Kumar,sports,Cricket Bat,9.0,NaN,0.0,20728.62,Net Banking,Returned
261,ORD-1107,2023-10-15,Customer_786,Jaipur,North,Divya Iyer,clothing,Formal Shirt,3.0,NaN,20.0,2753.28,Cash,Returned

Grouping

In [56]:
df.groupby("category")["unit_price"].sum()

category
Clothing            105273.88
Clothings             7140.84
Cloting               4407.70
Electronics        1193119.09
Electronis           22431.88
FURNITURE            52529.47
Furniture           533392.97
Furnitures           25841.72
Furnture             37279.98
OFFICE SUPPLIES      12374.12
Office Supplies     152953.97
Office Supply          362.94
Office supplies       3223.71
SPORTS                   0.00
Sport                 4463.54
Sports              219742.60
Sprots                 685.25
clothing              4084.37
electronic           26837.61
furniture            58799.79
office supplies        461.36
sports               17494.31
Name: unit_price, dtype: float64

In [58]:
df.groupby("unit_price").size()

unit_price
145.50      1
145.96      1
146.82      1
150.92      1
152.60      1
           ..
66604.54    1
66898.52    1
67522.59    1
67635.23    1
68006.47    1
Length: 230, dtype: int64

Extra Useful Commands

In [59]:
df.sample(5)

,order_id,order_date,customer_name,city,region,salesperson,category,product,quantity,unit_price,discount_pct,total_amount,payment_mode,status
219,ORD-1175,2023-09-29,Customer_753,Bhubaneswar,East,Sneha Patel,Furniture,Office Chair,4.0,8644.36,0.0,34577.44,Card,Delivered
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,ORD-1164,2023-01-27,Customer_471,Ahmedabad,West,Sneha Patel,FURNITURE,Bookshelf,7.0,4295.36,10.0,27060.77,UPI,Delivered
166,ORD-1124,2023-06-25,Customer_616,Mumbai,West,Priya Nair,Sports,Football,8.0,979.54,0.0,7836.32,NaN,Delivered
80,ORD-1145,10-02-2023,Customer_776,Pune,West,Divya Iyer,Electronics,Headphones,9.0,5401.67,10.0,43753.53,UPI,Delivered

In [60]:
df.nunique()

order_id         250
order_date       211
customer_name    215
city              16
region             8
salesperson        8
category          22
product           25
quantity          13
unit_price       230
discount_pct       5
total_amount     250
payment_mode      12
status             3
dtype: int64

In [61]:
df.value_counts()

order_id  order_date  customer_name     city        region  salesperson  category         product       quantity  unit_price  discount_pct  total_amount  payment_mode  status
ORD-1178  2023-10-18  Customer_443      Chandigarh  North   Priya Nair   Clothing         Sneakers      5.0       2662.59     0.0           13312.95      UPI           Returned     2
ORD-1088  2023-09-05  Customer_342      Guwahati    East    Priya Nair   Clothing         Jacket        5.0       3674.78     5.0           17455.21      Net Banking   Pending      2
ORD-1116  2023-10-22  Customer_687      Mumbai      West    Karan Singh  Electronics      Headphones    8.0       5699.16     0.0           45593.28      Net Banking   Returned     1
ORD-1121  2023-08-29  Customer_746      Ahmedabad   west    Neha Joshi   Sports           Cycle         6.0       14909.64    5.0           84984.95      UPI           Delivered    1
ORD-1123  2023-01-22  Customer_929      Lucknow     North   Neha Joshi   Sports           Cycle         8.0       15081.47    20.0          96521.41      Card          Delivered    1
                                                                                                                                                                                    ..
ORD-1117  11/13/2023  Customer_951      Kolkata     east    Neha Joshi   Electronics      Headphones    6.0       5665.73     5.0           32294.66      UPI           Delivered    1
ORD-1075  27-Jan-23   Customer_373      Jaipur      North   Sneha Patel  Furniture        Wardrobe      10.0      18225.74    15.0          154918.79     Card          Delivered    1
ORD-1215  11/21/2023    Customer_857    Kolkata     East    Ravi Kumar   Furniture        Office Chair  5.0       8398.00     5.0           39890.50      Net Banking   Delivered    1
ORD-1122  2023-01-30  Customer_951      Delhi       North   Divya Iyer   Office Supplies  File Cabinet  5.0       3184.61     15.0          13534.59      UPI           Delivered    1
ORD-1103  25/02/2023    Customer_829    Kolkata     East    Neha Joshi   Clothings        Formal Shirt  8.0       1191.15     15.0          8099.82       net banking   Delivered    1
Name: count, Length: 183, dtype: int64